# Generated by Django 5.1.1 on 2026-06-19 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_sleepsummary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notificationdata',
            name='user',
        ),
        migrations.RenameIndex(
            model_name='heartratesample',
            new_name='app_heartra_user_id_49d947_idx',
            old_name='app_heartrate_user_ts_idx',
        ),
        migrations.RenameIndex(
            model_name='stresssample',
            new_name='app_stresss_user_id_68a35e_idx',
            old_name='app_stress_user_ts_idx',
        ),
        migrations.DeleteModel(
            name='NotificationData',
        ),
    ]
