# Generated by Django 5.1.1 on 2026-06-22 20:26

import app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_add_mssd_fields_to_jitailog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EngagementLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('ema_opened', 'EMA Opened'), ('ema_dismissed', 'EMA Dismissed'), ('ema_completed', 'EMA Completed'), ('notification_tapped', 'Notification Tapped'), ('notification_dismissed', 'Notification Dismissed')], max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('game_clock_state', models.CharField(choices=[('pre', 'Pre-Game'), ('live', 'Live'), ('post', 'Post-Game')], default='pre', max_length=16)),
                ('jitai_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.jitailog')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='app_engagem_user_id_70d764_idx')],
            },
        ),
        migrations.CreateModel(
            name='PhoneTelemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=64)),
                ('event_type', models.CharField(choices=[('draft_started', 'Draft Started'), ('draft_deleted', 'Draft Deleted'), ('draft_submitted', 'Draft Submitted'), ('session_start', 'Session Start'), ('session_end', 'Session End')], max_length=64)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('game_clock_state', models.CharField(choices=[('pre', 'Pre-Game'), ('live', 'Live'), ('post', 'Post-Game')], default='pre', max_length=16)),
                ('screen_name', models.CharField(blank=True, max_length=64, null=True)),
                ('latency_ms', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True, validators=[app.models.validate_phone_metadata])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['user', 'occurred_at'], name='app_phonete_user_id_aa67a1_idx')],
            },
        ),
        migrations.CreateModel(
            name='SleepSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('light_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('deep_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('rem_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('awake_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sleep_score', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source', models.CharField(default='garmin_fitabase', max_length=32)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
            options={
                'unique_together': {('user', 'date')},
            },
        ),
    ]
