"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.1.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
# For accessing environment variables
import os
import dj_database_url
import sentry_sdk

# For accessing environment variables from your .env file
from dotenv import load_dotenv
from pathlib import Path as _Path
load_dotenv(_Path(__file__).resolve().parent.parent / '.env')

from pathlib import Path

from celery.schedules import crontab, schedule
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Use the PORT environment variable set by Heroku.
# Gunicorn (see Procfile) uses the dynamic port assigned by Heroku, or defaults to 8000 if PORT is not set.
# Running 'python manage.py runserver 0.0.0.0:8000' explicitly sets the port for local testing,
# while 'python manage.py runserver' defaults to the fallback port (8000).
PORT = os.getenv('PORT', '8000')

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

DASHBOARD_API_KEY = os.getenv('DASHBOARD_API_KEY', '')

SENTRY_DSN = os.getenv('SENTRY_DSN')
if SENTRY_DSN:
    sentry_sdk.init(
        dsn=SENTRY_DSN,
        send_default_pii=False,
        traces_sample_rate=float(os.getenv('SENTRY_TRACES_SAMPLE_RATE', '0.1')),
        environment=os.getenv('SENTRY_ENVIRONMENT', 'production' if not DEBUG else 'development'),
    )

ALLOWED_HOSTS = [
    'healthygatorsportsfan-84ee3c84673f.herokuapp.com',
    'healthygatorsportfan.herokuapp.com',
    'healthygatorsportfan-ab9271b02569.herokuapp.com',
    '127.0.0.1', 
    'localhost', 
    '192.168.68.124', 
    '192.168.4.168', 
    'b862-184-185-222-16.ngrok-free.app', 
    'sawfish-premium-unlikely.ngrok-free.app', 
    'strongly-inviting-stinkbug.ngrok-free.app', 
    'normal-elegant-corgi.ngrok-free.app',
    'tuna-fleet-hamster.ngrok-free.app'
]

# Add Cloud Run domain pattern
if os.getenv('K_SERVICE'):
    ALLOWED_HOSTS.append(f'{os.getenv("K_SERVICE")}-{os.getenv("K_REVISION")}.{os.getenv("K_CONFIGURATION")}-{os.getenv("GOOGLE_CLOUD_PROJECT")}.uc.r.appspot.com')
    ALLOWED_HOSTS.append(f'{os.getenv("K_SERVICE")}-{os.getenv("GOOGLE_CLOUD_PROJECT")}.uc.r.appspot.com')
if os.getenv('HEROKU_APP_NAME'):
    ALLOWED_HOSTS.append(f'{os.getenv("HEROKU_APP_NAME")}.herokuapp.com')


# Application definition
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'app',
    'rest_framework',
    'corsheaders',
    'rest_framework_simplejwt',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=30),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),
    "AUTH_HEADER_TYPES": ("Bearer",),

    # "USER_ID_FIELD": "user_id",
    # "USER_ID_CLAIM": "user_id",
}

PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher',
    'django.contrib.auth.hashers.ScryptPasswordHasher',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
]

CORS_ALLOW_ALL_ORIGINS = True 

ROOT_URLCONF = 'project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

# Database configuration
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

database_url = os.getenv('DATABASE_URL')

if database_url:
    DATABASES = {
        'default': dj_database_url.config(
            default=database_url,
            conn_max_age=600,
            conn_health_checks=True,
            ssl_require=database_url.startswith('postgres://') or database_url.startswith('postgresql://'),
        )
    }
elif os.getenv('K_SERVICE'):
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DATABASE_NAME', 'react_db'),
            'USER': os.getenv('DATABASE_USER', 'postgres'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD'),
            'HOST': f'/cloudsql/{os.getenv("CLOUD_SQL_CONNECTION_NAME")}',
            'PORT': '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': os.getenv('DATABASE_NAME'),
            'USER': os.getenv('DATABASE_USER'),
            'PASSWORD': os.getenv('DATABASE_PASSWORD'),
            'HOST': os.getenv('DATABASE_HOST', 'localhost'),
            'PORT': os.getenv('DATABASE_PORT', '5432'),
        }
    }

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles') # backend/staticfiles

STATIC_DIR = os.path.join(BASE_DIR, 'static')
STATICFILES_DIRS = [STATIC_DIR] if os.path.isdir(STATIC_DIR) else []
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CSRF_TRUSTED_ORIGINS = [
    'https://b862-184-185-222-16.ngrok-free.app',
    'https://normal-elegant-corgi.ngrok-free.app',
    'https://sawfish-premium-unlikely.ngrok-free.app',
    'https://strongly-inviting-stinkbug.ngrok-free.app',
    'https://healthygatorsportsfan-84ee3c84673f.herokuapp.com',
    'https://healthygatorsportfan.herokuapp.com',
    'https://healthygatorsportfan-ab9271b02569.herokuapp.com',
    'https://tuna-fleet-hamster.ngrok-free.app'
]
if os.getenv('HEROKU_APP_NAME'):
    CSRF_TRUSTED_ORIGINS.append(f'https://{os.getenv("HEROKU_APP_NAME")}.herokuapp.com')

REDIS_URL = os.getenv('REDIS_URL', 'redis://localhost:6379/0')
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL

CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'

CELERY_BEAT_SCHEDULE = {
    'ingest-wearable-data': {
        'task': 'app.tasks.ingest_wearable_data',
        'schedule': schedule(180.0),
    },
    'evaluate-jitai-triggers': {
        'task': 'app.tasks.evaluate_jitai_triggers',
        'schedule': schedule(180.0),
    },
    'send-checkin-reminders': {
        'task': 'app.tasks.send_checkin_reminders',
        'schedule': schedule(180.0),
    },
}

CACHES = {
    'default': {
        'BACKEND': 'django_redis.cache.RedisCache',
        'LOCATION': REDIS_URL,
        'OPTIONS': {
            'CLIENT_CLASS': 'django_redis.client.DefaultClient',
        }
    }
}
