# Generated by Django 5.1.1 on 2026-09-10 18:32

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("app", "0043_jitailog_category_drawn_jitailog_evaluated_items_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MetricsCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "as_of",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "phase_filter",
                    models.CharField(
                        choices=[
                            ("all", "All participants"),
                            ("phase1", "Phase 1"),
                            ("phase2", "Phase 2"),
                        ],
                        max_length=16,
                    ),
                ),
                ("n_participants", models.IntegerField()),
                ("n_active", models.IntegerField()),
                ("benchmarks", models.JSONField(blank=True, null=True)),
                ("series_14d", models.JSONField(blank=True, null=True)),
                ("decision_points_n", models.IntegerField(blank=True, null=True)),
                ("eligible_n", models.IntegerField(blank=True, null=True)),
                ("sent_n", models.IntegerField(blank=True, null=True)),
                ("delivered_n", models.IntegerField(blank=True, null=True)),
                ("cooldown_violations_n", models.IntegerField(blank=True, null=True)),
                ("runin_violations_n", models.IntegerField(blank=True, null=True)),
                ("cap_hit_days", models.IntegerField(blank=True, null=True)),
                ("delivery_failures_n", models.IntegerField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-as_of"],
                "indexes": [
                    models.Index(
                        fields=["phase_filter", "-as_of"],
                        name="dashboard_m_phase_f_37d2a3_idx",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricsParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("enrolled_at", models.DateTimeField(blank=True, null=True)),
                ("day1_date", models.DateField(blank=True, null=True)),
                ("study_day_now", models.SmallIntegerField(blank=True, null=True)),
                (
                    "phase",
                    models.CharField(
                        choices=[
                            ("pre_enrollment", "Pre-enrollment"),
                            ("run_in", "Run-in"),
                            ("mrt", "Micro-randomized"),
                            ("complete", "Complete"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        max_length=16,
                    ),
                ),
                ("is_enrolled_snapshot", models.BooleanField()),
                (
                    "first_seen_not_enrolled_at",
                    models.DateTimeField(blank=True, null=True),
                ),
                ("last_ema_at", models.DateTimeField(blank=True, null=True)),
                ("last_sync_at", models.DateTimeField(blank=True, null=True)),
                ("active_retention", models.BooleanField(blank=True, null=True)),
                ("risk_score", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("slot_coverage_rate", models.FloatField(blank=True, null=True)),
                ("slot_coverage_num", models.IntegerField(blank=True, null=True)),
                ("slot_coverage_den", models.IntegerField(blank=True, null=True)),
                ("prompt_response_rate", models.FloatField(blank=True, null=True)),
                ("prompt_response_num", models.IntegerField(blank=True, null=True)),
                ("prompt_response_den", models.IntegerField(blank=True, null=True)),
                ("wear_rate", models.FloatField(blank=True, null=True)),
                ("wear_num", models.IntegerField(blank=True, null=True)),
                ("wear_den", models.IntegerField(blank=True, null=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics_participant",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "ordering": ["user"],
            },
        ),
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rule_id", models.CharField(db_index=True, max_length=64)),
                (
                    "severity",
                    models.CharField(
                        choices=[("critical", "Critical"), ("warning", "Warning")],
                        max_length=16,
                    ),
                ),
                (
                    "fired_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "resolved_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("payload", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-fired_at"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("resolved_at__isnull", True)),
                        fields=("user", "rule_id"),
                        name="uniq_open_alert_per_user_rule",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(
                            ("resolved_at__isnull", True), ("user__isnull", True)
                        ),
                        fields=("rule_id",),
                        name="uniq_open_cohort_alert_per_rule",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MetricsDaily",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("study_day", models.SmallIntegerField()),
                ("local_date", models.DateField(db_index=True)),
                ("is_run_in", models.BooleanField()),
                ("is_active_day", models.BooleanField()),
                ("computed_at", models.DateTimeField(auto_now=True)),
                ("item_bank_version", models.CharField(max_length=16)),
                (
                    "ema_scheduled_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "ema_jitai_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "ema_post_prompt_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "slots_expected",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "slots_covered",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "slots_reminded_uncovered",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "slots_silent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "reminders_sent",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "reminders_per_checkin_median",
                    models.FloatField(blank=True, null=True),
                ),
                ("completeness_mean", models.FloatField(blank=True, null=True)),
                (
                    "ema_missing_b1b2_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "decision_points_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("eligible_n", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("sent_n", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "delivered_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("cap_hit", models.BooleanField(blank=True, null=True)),
                ("min_gap_min", models.IntegerField(blank=True, null=True)),
                (
                    "cooldown_violations_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "runin_violation_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "prompt_opened_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "prompt_acted_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "prompt_dismissed_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "outcome_captured_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("wear_valid_pct", models.FloatField(blank=True, null=True)),
                ("wear_gap_pct", models.FloatField(blank=True, null=True)),
                (
                    "gaps_gt2h_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("max_gap_min", models.IntegerField(blank=True, null=True)),
                (
                    "hr_minutes_valid",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("last_sync_age_h_eod", models.FloatField(blank=True, null=True)),
                ("clock_skew_p95_ms", models.IntegerField(blank=True, null=True)),
                (
                    "delivery_failures_n",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metrics_daily",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "ordering": ["user", "study_day"],
                "indexes": [
                    models.Index(
                        fields=["user", "local_date"],
                        name="dashboard_m_user_id_bed8b8_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "study_day"), name="uniq_metrics_daily_user_day"
                    )
                ],
            },
        ),
    ]
