# Generated by Django 6.0.6 on 2026-09-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_metricscohort_funnel_metricscohort_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='metricsdaily',
            name='suppressed_n',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
