# Generated by Django 5.1.1 on 2026-09-10 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricsparticipant",
            name="risk_components",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
