# Generated by Django 5.1.1 on 2026-09-11 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0002_metricsparticipant_risk_components"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert",
            name="severity",
            field=models.CharField(
                choices=[
                    ("critical", "Critical"),
                    ("high", "High"),
                    ("warning", "Warning"),
                ],
                max_length=16,
            ),
        ),
    ]
