# Generated by Django 5.1.1 on 2026-09-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0003_alter_alert_severity"),
    ]

    operations = [
        migrations.AddField(
            model_name="metricscohort",
            name="funnel",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="metricscohort",
            name="integrity",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
