# Generated by Django 5.1.1 on 2026-06-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_user_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='fitbit_access_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fitbit_refresh_token',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fitbit_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='fitbit_user_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
