# Generated by Django 5.1.1 on 2026-06-04 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_user_fitbit_access_token_user_fitbit_refresh_token_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WearableDevice',
            fields=[
                ('device_id', models.AutoField(primary_key=True, serialize=False)),
                ('fitbit_device_id', models.CharField(max_length=64)),
                ('device_type', models.CharField(max_length=32)),
                ('device_name', models.CharField(max_length=64)),
                ('last_synced_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
