# Generated by Django 5.1.1 on 2026-06-04 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_wearabledevice'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateSample',
            fields=[
                ('sample_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('bpm', models.PositiveSmallIntegerField()),
                ('zone', models.CharField(choices=[('out_of_range', 'Out of Range'), ('fat_burn', 'Fat Burn'), ('cardio', 'Cardio'), ('peak', 'Peak')], max_length=20)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wearabledevice')),
            ],
        ),
        migrations.CreateModel(
            name='ActivitySummary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('steps', models.PositiveIntegerField(blank=True, null=True)),
                ('active_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('calories_burned', models.PositiveIntegerField(blank=True, null=True)),
                ('distance_km', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.wearabledevice')),
            ],
            options={
                'unique_together': {('device', 'date')},
            },
        ),
    ]
