# Generated by Django 5.1.1 on 2026-06-04 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_ema'),
    ]

    operations = [
        migrations.CreateModel(
            name='JITAILog',
            fields=[
                ('log_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('trigger_reason', models.CharField(max_length=100)),
                ('volatility_score', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('threshold_used', models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True)),
                ('prompt_status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('dismissed', 'Dismissed'), ('acted_on', 'Acted On')], default='sent', max_length=20)),
                ('prompt_count', models.PositiveIntegerField(default=0)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('interacted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
