# Generated by Django 5.1.1 on 2026-06-19 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_drop_notificationdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitailog',
            name='ema',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ema'),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='observed_mssd',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='send_prompt',
            field=models.BooleanField(default=True),
        ),
    ]
