# Generated by Django 5.1.1 on 2026-07-01 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_labfront_rename_drop_sleep_strip_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='goal_to_feel_better',
        ),
        migrations.RemoveField(
            model_name='user',
            name='goal_to_lose_weight',
        ),
        migrations.RemoveField(
            model_name='user',
            name='goal_weight',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height_feet',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height_inches',
        ),
    ]
