# Generated by Django 6.0.6 on 2026-07-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_drop_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='engagementlog',
            name='game_clock_state',
        ),
        migrations.RemoveField(
            model_name='phonetelemetry',
            name='game_clock_state',
        ),
    ]
