# Generated by Django 6.0.6 on 2026-07-06 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_drop_game_clock_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitailog',
            name='decision_point_id',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='randomization_draw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='randomization_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jitailog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('interacted', 'Interacted'), ('failed', 'Failed'), ('not_sent', 'Not Sent')], default='pending', max_length=16),
        ),
    ]
