# Generated by Django 5.1.1 on 2026-07-16 23:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0035_jitailog_mrt_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="jitailog",
            name="decision_made_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="jitailog",
            name="delivery_error",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jitailog",
            name="delivery_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("not_sent", "Not Sent"),
                    ("accepted_by_expo", "Accepted by Expo"),
                    ("received_on_device", "Received on Device"),
                    ("failed", "Failed"),
                ],
                db_index=True,
                default="pending",
                max_length=32,
            ),
        ),
        migrations.AddField(
            model_name="jitailog",
            name="device_received_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="jitailog",
            name="push_sent_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="jitailog",
            name="receipt_app_state",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="jitailog",
            name="receipt_platform",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.AddField(
            model_name="jitailog",
            name="receipt_reported_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
