# Generated by Django 6.0.6 on 2026-07-14 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_jitailog_mrt_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitailog',
            name='eligible_prompt_ids',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='ema_energy',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='ema_mood',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='ema_stress',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='trigger_signal',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
