# Generated by Django 5.1.1 on 2026-07-16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_jitailog_decision_made_at_jitailog_delivery_error_and_more'),
        ('app', '0036_jitailog_prompt_fields'),
    ]

    operations = []
