# Generated by Django 6.0.6 on 2026-08-25 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_checkinreminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitailog',
            name='arm_randomization_draw',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='arm_randomization_probability',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='message_arm',
            field=models.CharField(blank=True, choices=[('coping', 'Coping Message'), ('control', 'Active Control')], max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='ema',
            name='ema_type',
            field=models.CharField(choices=[('scheduled_check_in', 'Scheduled Check-in'), ('post_prompt', 'Post-prompt Outcome Window'), ('extra_check_in', 'Extra Check-in'), ('prompt_feedback', 'Prompt Feedback')], default='scheduled_check_in', max_length=32),
        ),
        migrations.AlterField(
            model_name='ema',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('expired', 'Expired'), ('dismissed', 'Dismissed')], default='pending', max_length=16),
        ),
    ]
