# Generated by Django 6.0.6 on 2026-09-07 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0042_jitailog_arm_randomization_draw_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitailog',
            name='category_drawn',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='evaluated_items',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='fallback_reason',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='matched_categories',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
