# Generated by Django 5.1.1 on 2026-09-10 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0043_jitailog_category_drawn_jitailog_evaluated_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ema",
            name="served_sub_item_ids",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
