# Generated by Codex on 2026-09-10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_jitailog_category_drawn_jitailog_evaluated_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitailog',
            name='receipt_event_id',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True, unique=True),
        ),
    ]
