# Generated by Django 5.1.1 on 2026-09-10 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0044_ema_served_sub_item_ids"),
        ("app", "0044_jitailog_receipt_event_id"),
    ]

    operations = []
