# Generated by Django 5.1.1 on 2026-09-10 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0045_merge_20260910_2127"),
    ]

    operations = [
        migrations.AddField(
            model_name="jitailog",
            name="threshold_at_decision",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jitailog",
            name="threshold_source",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
        migrations.CreateModel(
            name="WearableSync",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observed_at", models.DateTimeField(db_index=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("ingest", "Labfront ingestion"),
                            ("client", "Mobile client"),
                        ],
                        max_length=16,
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("samples_written", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="wearable_syncs",
                        to="app.user",
                    ),
                ),
            ],
            options={
                "ordering": ["-observed_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "observed_at"],
                        name="app_wearabl_user_id_536b2e_idx",
                    )
                ],
            },
        ),
    ]
