# Generated by Django 5.1.1 on 2026-09-17 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0046_jitailog_threshold_at_decision_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jitailog",
            name="hrv_class_at_trigger",
            field=models.CharField(
                blank=True,
                choices=[("Low", "Low"), ("Balanced", "Balanced"), ("High", "High")],
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="jitailog",
            name="rmssd_at_trigger",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jitailog",
            name="rmssd_baseline_at_trigger",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="HRVSample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("rmssd_ms", models.FloatField()),
                ("beat_count", models.PositiveSmallIntegerField(default=0)),
                ("source", models.CharField(default="garmin_labfront", max_length=32)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.user"
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(
                        fields=["user", "timestamp"],
                        name="app_hrvsamp_user_id_173906_idx",
                    )
                ],
            },
        ),
    ]
