# Generated by Django 6.0.6 on 2026-09-22 00:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0047_hrvsample_and_jitai_hrv_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitailog',
            name='suppression_reason',
            field=models.CharField(blank=True, choices=[('run_in', 'Run-in period'), ('distress_baseline', 'Distress override (baseline screen)'), ('distress_momentary', 'Distress override (check-in)')], db_index=True, default='', max_length=32),
        ),
        migrations.CreateModel(
            name='DistressFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('baseline', 'Baseline screen'), ('momentary', 'Check-in')], max_length=16)),
                ('signals', models.JSONField(blank=True, default=list)),
                ('raised_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('contact_documented_at', models.DateTimeField(blank=True, null=True)),
                ('ema', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.ema')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='distress_flags', to='app.user')),
            ],
            options={
                'ordering': ['-raised_at'],
                'indexes': [models.Index(fields=['user', 'raised_at'], name='app_distres_user_id_695728_idx')],
            },
        ),
    ]
