# Generated by Django 6.0.6 on 2026-09-25 01:20

from django.db import migrations, models


def backfill_suppressed_labels(apps, schema_editor):
    JITAILog = apps.get_model('app', 'JITAILog')
    JITAILog.objects.filter(
        suppression_reason='', trigger_reason='run-in period',
    ).update(suppression_reason='run_in')
    JITAILog.objects.exclude(suppression_reason='').filter(
        status='not_sent',
    ).update(status='suppressed')
    JITAILog.objects.exclude(suppression_reason='').filter(
        delivery_status='not_sent',
    ).update(delivery_status='suppressed')


def restore_not_sent_labels(apps, schema_editor):
    JITAILog = apps.get_model('app', 'JITAILog')
    JITAILog.objects.filter(status='suppressed').update(status='not_sent')
    JITAILog.objects.filter(delivery_status='suppressed').update(delivery_status='not_sent')


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0048_distressflag_and_jitailog_suppression_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jitailog',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_sent', 'Not Sent'), ('suppressed', 'Suppressed'), ('accepted_by_expo', 'Accepted by Expo'), ('received_on_device', 'Received on Device'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
        migrations.AlterField(
            model_name='jitailog',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('opened', 'Opened'), ('interacted', 'Interacted'), ('failed', 'Failed'), ('not_sent', 'Not Sent'), ('suppressed', 'Suppressed')], default='pending', max_length=16),
        ),
        migrations.RunPython(backfill_suppressed_labels, restore_not_sent_labels),
    ]
