# Generated by Django 5.1.1 on 2026-09-29 22:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0049_suppressed_status_and_backfill"),
    ]

    operations = [
        migrations.AddField(
            model_name="checkinreminder",
            name="jitai_log",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="outcome_reminders",
                to="app.jitailog",
            ),
        ),
        migrations.AlterField(
            model_name="checkinreminder",
            name="daily_count_at_send",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
