# Generated by Django 6.0.6 on 2026-10-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0049_suppressed_status_and_backfill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jitailog',
            name='suppression_reason',
            field=models.CharField(blank=True, choices=[('run_in', 'Run-in period'), ('distress_baseline', 'Distress override (baseline screen)'), ('distress_momentary', 'Distress override (check-in)'), ('cooldown', 'Cooldown active'), ('daily_cap', 'Daily cap reached')], db_index=True, default='', max_length=32),
        ),
    ]
