# Generated by Django 6.0.6 on 2026-10-01 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0050_alter_jitailog_suppression_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='study_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
