# Generated by Django 5.1.1 on 2026-10-05 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0050_checkinreminder_outcome_window"),
        ("app", "0051_user_study_id"),
    ]

    operations = []
