# Generated by Django 6.0.6 on 2026-10-08 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0052_merge_20261005_0027'),
    ]

    operations = [
        migrations.AddField(
            model_name='jitailog',
            name='expo_receipt_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='expo_receipt_error',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='expo_receipt_status',
            field=models.CharField(blank=True, default='', max_length=16),
        ),
        migrations.AddField(
            model_name='jitailog',
            name='expo_ticket_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='jitailog',
            name='delivery_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('not_sent', 'Not Sent'), ('suppressed', 'Suppressed'), ('accepted_by_expo', 'Accepted by Expo'), ('handed_to_provider', 'Handed to Apple/Google'), ('received_on_device', 'Received on Device'), ('failed', 'Failed')], db_index=True, default='pending', max_length=32),
        ),
    ]
